apiVersion: v1
kind: Service
metadata:
  name: sequential-id-api-service
  labels:
    app: sequential-id-api
    component: api
spec:
  selector:
    app: sequential-id-api
  ports:
  - name: rest-api
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc-api
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: metrics
    port: 2112
    targetPort: 2112
    protocol: TCP
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: sequential-id-worker-service
  labels:
    app: sequential-id-worker
    component: worker
spec:
  selector:
    app: sequential-id-worker
  ports:
  - name: metrics
    port: 2113
    targetPort: 2113
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: management
    port: 15672
    targetPort: 15672
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
