// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: api/proto/sequential_id.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_Status int32

const (
	HealthResponse_SERVING         HealthResponse_Status = 0
	HealthResponse_NOT_SERVING     HealthResponse_Status = 1
	HealthResponse_SERVICE_UNKNOWN HealthResponse_Status = 2
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "SERVING",
		1: "NOT_SERVING",
		2: "SERVICE_UNKNOWN",
	}
	HealthResponse_Status_value = map[string]int32{
		"SERVING":         0,
		"NOT_SERVING":     1,
		"SERVICE_UNKNOWN": 2,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_sequential_id_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_api_proto_sequential_id_proto_enumTypes[0]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{10, 0}
}

// Request to get next sequential ID
type GetNextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextRequest) Reset() {
	*x = GetNextRequest{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextRequest) ProtoMessage() {}

func (x *GetNextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextRequest.ProtoReflect.Descriptor instead.
func (*GetNextRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetNextRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *GetNextRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetNextRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// Response with next sequential ID
type GetNextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullNumber    string                 `protobuf:"bytes,1,opt,name=full_number,json=fullNumber,proto3" json:"full_number,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Counter       int64                  `protobuf:"varint,3,opt,name=counter,proto3" json:"counter,omitempty"`
	GeneratedAt   string                 `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	MessageId     string                 `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextResponse) Reset() {
	*x = GetNextResponse{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextResponse) ProtoMessage() {}

func (x *GetNextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextResponse.ProtoReflect.Descriptor instead.
func (*GetNextResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{1}
}

func (x *GetNextResponse) GetFullNumber() string {
	if x != nil {
		return x.FullNumber
	}
	return ""
}

func (x *GetNextResponse) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *GetNextResponse) GetCounter() int64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *GetNextResponse) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *GetNextResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// Request to get batch of sequential IDs
type GetNextBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextBatchRequest) Reset() {
	*x = GetNextBatchRequest{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextBatchRequest) ProtoMessage() {}

func (x *GetNextBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextBatchRequest.ProtoReflect.Descriptor instead.
func (*GetNextBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{2}
}

func (x *GetNextBatchRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *GetNextBatchRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetNextBatchRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetNextBatchRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// Response with batch of sequential IDs
type GetNextBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullNumbers   []string               `protobuf:"bytes,1,rep,name=full_numbers,json=fullNumbers,proto3" json:"full_numbers,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	StartCounter  int64                  `protobuf:"varint,3,opt,name=start_counter,json=startCounter,proto3" json:"start_counter,omitempty"`
	EndCounter    int64                  `protobuf:"varint,4,opt,name=end_counter,json=endCounter,proto3" json:"end_counter,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	GeneratedAt   string                 `protobuf:"bytes,6,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	BatchId       string                 `protobuf:"bytes,7,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextBatchResponse) Reset() {
	*x = GetNextBatchResponse{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextBatchResponse) ProtoMessage() {}

func (x *GetNextBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextBatchResponse.ProtoReflect.Descriptor instead.
func (*GetNextBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{3}
}

func (x *GetNextBatchResponse) GetFullNumbers() []string {
	if x != nil {
		return x.FullNumbers
	}
	return nil
}

func (x *GetNextBatchResponse) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *GetNextBatchResponse) GetStartCounter() int64 {
	if x != nil {
		return x.StartCounter
	}
	return 0
}

func (x *GetNextBatchResponse) GetEndCounter() int64 {
	if x != nil {
		return x.EndCounter
	}
	return 0
}

func (x *GetNextBatchResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetNextBatchResponse) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *GetNextBatchResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

// Request to reset counter
type ResetCounterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	NewValue      int64                  `protobuf:"varint,2,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetCounterRequest) Reset() {
	*x = ResetCounterRequest{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetCounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetCounterRequest) ProtoMessage() {}

func (x *ResetCounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetCounterRequest.ProtoReflect.Descriptor instead.
func (*ResetCounterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{4}
}

func (x *ResetCounterRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ResetCounterRequest) GetNewValue() int64 {
	if x != nil {
		return x.NewValue
	}
	return 0
}

func (x *ResetCounterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResetCounterRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ResetCounterRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// Response for reset counter
type ResetCounterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	OldValue      int64                  `protobuf:"varint,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue      int64                  `protobuf:"varint,4,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetCounterResponse) Reset() {
	*x = ResetCounterResponse{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetCounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetCounterResponse) ProtoMessage() {}

func (x *ResetCounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetCounterResponse.ProtoReflect.Descriptor instead.
func (*ResetCounterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{5}
}

func (x *ResetCounterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetCounterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResetCounterResponse) GetOldValue() int64 {
	if x != nil {
		return x.OldValue
	}
	return 0
}

func (x *ResetCounterResponse) GetNewValue() int64 {
	if x != nil {
		return x.NewValue
	}
	return 0
}

// Request to get status
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

// Response with status information
type GetStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Prefix         string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	CurrentCounter int64                  `protobuf:"varint,2,opt,name=current_counter,json=currentCounter,proto3" json:"current_counter,omitempty"`
	IsActive       bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	LastGenerated  string                 `protobuf:"bytes,4,opt,name=last_generated,json=lastGenerated,proto3" json:"last_generated,omitempty"`
	TotalGenerated int64                  `protobuf:"varint,5,opt,name=total_generated,json=totalGenerated,proto3" json:"total_generated,omitempty"`
	Config         *ConfigInfo            `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusResponse) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *GetStatusResponse) GetCurrentCounter() int64 {
	if x != nil {
		return x.CurrentCounter
	}
	return 0
}

func (x *GetStatusResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetStatusResponse) GetLastGenerated() string {
	if x != nil {
		return x.LastGenerated
	}
	return ""
}

func (x *GetStatusResponse) GetTotalGenerated() int64 {
	if x != nil {
		return x.TotalGenerated
	}
	return 0
}

func (x *GetStatusResponse) GetConfig() *ConfigInfo {
	if x != nil {
		return x.Config
	}
	return nil
}

// Configuration information
type ConfigInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Padding       int32                  `protobuf:"varint,3,opt,name=padding,proto3" json:"padding,omitempty"`
	Separator     string                 `protobuf:"bytes,4,opt,name=separator,proto3" json:"separator,omitempty"`
	InitialValue  int64                  `protobuf:"varint,5,opt,name=initial_value,json=initialValue,proto3" json:"initial_value,omitempty"`
	MaxValue      int64                  `protobuf:"varint,6,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigInfo) Reset() {
	*x = ConfigInfo{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigInfo) ProtoMessage() {}

func (x *ConfigInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigInfo.ProtoReflect.Descriptor instead.
func (*ConfigInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigInfo) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ConfigInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ConfigInfo) GetPadding() int32 {
	if x != nil {
		return x.Padding
	}
	return 0
}

func (x *ConfigInfo) GetSeparator() string {
	if x != nil {
		return x.Separator
	}
	return ""
}

func (x *ConfigInfo) GetInitialValue() int64 {
	if x != nil {
		return x.InitialValue
	}
	return 0
}

func (x *ConfigInfo) GetMaxValue() int64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *ConfigInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ConfigInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{9}
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=sequentialid.HealthResponse_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_SERVING
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// Request to get configuration
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{11}
}

func (x *GetConfigRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

// Response with configuration
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigInfo            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{12}
}

func (x *GetConfigResponse) GetConfig() *ConfigInfo {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfigResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Request to update configuration
type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigInfo            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateConfigRequest) GetConfig() *ConfigInfo {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateConfigRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdateConfigRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// Response for update configuration
type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Config        *ConfigInfo            `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_api_proto_sequential_id_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sequential_id_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_sequential_id_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateConfigResponse) GetConfig() *ConfigInfo {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_api_proto_sequential_id_proto protoreflect.FileDescriptor

const file_api_proto_sequential_id_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/sequential_id.proto\x12\fsequentialid\"l\n" +
	"\x0eGetNextRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"\xa6\x01\n" +
	"\x0fGetNextResponse\x12\x1f\n" +
	"\vfull_number\x18\x01 \x01(\tR\n" +
	"fullNumber\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x18\n" +
	"\acounter\x18\x03 \x01(\x03R\acounter\x12!\n" +
	"\fgenerated_at\x18\x04 \x01(\tR\vgeneratedAt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x05 \x01(\tR\tmessageId\"\x87\x01\n" +
	"\x13GetNextBatchRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\"\xeb\x01\n" +
	"\x14GetNextBatchResponse\x12!\n" +
	"\ffull_numbers\x18\x01 \x03(\tR\vfullNumbers\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12#\n" +
	"\rstart_counter\x18\x03 \x01(\x03R\fstartCounter\x12\x1f\n" +
	"\vend_counter\x18\x04 \x01(\x03R\n" +
	"endCounter\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12!\n" +
	"\fgenerated_at\x18\x06 \x01(\tR\vgeneratedAt\x12\x19\n" +
	"\bbatch_id\x18\a \x01(\tR\abatchId\"\xa6\x01\n" +
	"\x13ResetCounterRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x1b\n" +
	"\tnew_value\x18\x02 \x01(\x03R\bnewValue\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\x84\x01\n" +
	"\x14ResetCounterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\told_value\x18\x03 \x01(\x03R\boldValue\x12\x1b\n" +
	"\tnew_value\x18\x04 \x01(\x03R\bnewValue\"*\n" +
	"\x10GetStatusRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"\xf3\x01\n" +
	"\x11GetStatusResponse\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12'\n" +
	"\x0fcurrent_counter\x18\x02 \x01(\x03R\x0ecurrentCounter\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12%\n" +
	"\x0elast_generated\x18\x04 \x01(\tR\rlastGenerated\x12'\n" +
	"\x0ftotal_generated\x18\x05 \x01(\x03R\x0etotalGenerated\x120\n" +
	"\x06config\x18\x06 \x01(\v2\x18.sequentialid.ConfigInfoR\x06config\"\xf5\x01\n" +
	"\n" +
	"ConfigInfo\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x18\n" +
	"\apadding\x18\x03 \x01(\x05R\apadding\x12\x1c\n" +
	"\tseparator\x18\x04 \x01(\tR\tseparator\x12#\n" +
	"\rinitial_value\x18\x05 \x01(\x03R\finitialValue\x12\x1b\n" +
	"\tmax_value\x18\x06 \x01(\x03R\bmaxValue\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"\x0f\n" +
	"\rHealthRequest\"\xa5\x02\n" +
	"\x0eHealthResponse\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.sequentialid.HealthResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12C\n" +
	"\adetails\x18\x03 \x03(\v2).sequentialid.HealthResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x06Status\x12\v\n" +
	"\aSERVING\x10\x00\x12\x0f\n" +
	"\vNOT_SERVING\x10\x01\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x02\"*\n" +
	"\x10GetConfigRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"[\n" +
	"\x11GetConfigResponse\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x18.sequentialid.ConfigInfoR\x06config\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x8b\x01\n" +
	"\x13UpdateConfigRequest\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x18.sequentialid.ConfigInfoR\x06config\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"|\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x06config\x18\x03 \x01(\v2\x18.sequentialid.ConfigInfoR\x06config2\xc3\x04\n" +
	"\x13SequentialIDService\x12F\n" +
	"\aGetNext\x12\x1c.sequentialid.GetNextRequest\x1a\x1d.sequentialid.GetNextResponse\x12U\n" +
	"\fGetNextBatch\x12!.sequentialid.GetNextBatchRequest\x1a\".sequentialid.GetNextBatchResponse\x12U\n" +
	"\fResetCounter\x12!.sequentialid.ResetCounterRequest\x1a\".sequentialid.ResetCounterResponse\x12L\n" +
	"\tGetStatus\x12\x1e.sequentialid.GetStatusRequest\x1a\x1f.sequentialid.GetStatusResponse\x12C\n" +
	"\x06Health\x12\x1b.sequentialid.HealthRequest\x1a\x1c.sequentialid.HealthResponse\x12L\n" +
	"\tGetConfig\x12\x1e.sequentialid.GetConfigRequest\x1a\x1f.sequentialid.GetConfigResponse\x12U\n" +
	"\fUpdateConfig\x12!.sequentialid.UpdateConfigRequest\x1a\".sequentialid.UpdateConfigResponseBHZFgithub.com/putram11/sequential-id-counter-service/internal/api/grpc/pbb\x06proto3"

var (
	file_api_proto_sequential_id_proto_rawDescOnce sync.Once
	file_api_proto_sequential_id_proto_rawDescData []byte
)

func file_api_proto_sequential_id_proto_rawDescGZIP() []byte {
	file_api_proto_sequential_id_proto_rawDescOnce.Do(func() {
		file_api_proto_sequential_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sequential_id_proto_rawDesc), len(file_api_proto_sequential_id_proto_rawDesc)))
	})
	return file_api_proto_sequential_id_proto_rawDescData
}

var file_api_proto_sequential_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_sequential_id_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_sequential_id_proto_goTypes = []any{
	(HealthResponse_Status)(0),   // 0: sequentialid.HealthResponse.Status
	(*GetNextRequest)(nil),       // 1: sequentialid.GetNextRequest
	(*GetNextResponse)(nil),      // 2: sequentialid.GetNextResponse
	(*GetNextBatchRequest)(nil),  // 3: sequentialid.GetNextBatchRequest
	(*GetNextBatchResponse)(nil), // 4: sequentialid.GetNextBatchResponse
	(*ResetCounterRequest)(nil),  // 5: sequentialid.ResetCounterRequest
	(*ResetCounterResponse)(nil), // 6: sequentialid.ResetCounterResponse
	(*GetStatusRequest)(nil),     // 7: sequentialid.GetStatusRequest
	(*GetStatusResponse)(nil),    // 8: sequentialid.GetStatusResponse
	(*ConfigInfo)(nil),           // 9: sequentialid.ConfigInfo
	(*HealthRequest)(nil),        // 10: sequentialid.HealthRequest
	(*HealthResponse)(nil),       // 11: sequentialid.HealthResponse
	(*GetConfigRequest)(nil),     // 12: sequentialid.GetConfigRequest
	(*GetConfigResponse)(nil),    // 13: sequentialid.GetConfigResponse
	(*UpdateConfigRequest)(nil),  // 14: sequentialid.UpdateConfigRequest
	(*UpdateConfigResponse)(nil), // 15: sequentialid.UpdateConfigResponse
	nil,                          // 16: sequentialid.HealthResponse.DetailsEntry
}
var file_api_proto_sequential_id_proto_depIdxs = []int32{
	9,  // 0: sequentialid.GetStatusResponse.config:type_name -> sequentialid.ConfigInfo
	0,  // 1: sequentialid.HealthResponse.status:type_name -> sequentialid.HealthResponse.Status
	16, // 2: sequentialid.HealthResponse.details:type_name -> sequentialid.HealthResponse.DetailsEntry
	9,  // 3: sequentialid.GetConfigResponse.config:type_name -> sequentialid.ConfigInfo
	9,  // 4: sequentialid.UpdateConfigRequest.config:type_name -> sequentialid.ConfigInfo
	9,  // 5: sequentialid.UpdateConfigResponse.config:type_name -> sequentialid.ConfigInfo
	1,  // 6: sequentialid.SequentialIDService.GetNext:input_type -> sequentialid.GetNextRequest
	3,  // 7: sequentialid.SequentialIDService.GetNextBatch:input_type -> sequentialid.GetNextBatchRequest
	5,  // 8: sequentialid.SequentialIDService.ResetCounter:input_type -> sequentialid.ResetCounterRequest
	7,  // 9: sequentialid.SequentialIDService.GetStatus:input_type -> sequentialid.GetStatusRequest
	10, // 10: sequentialid.SequentialIDService.Health:input_type -> sequentialid.HealthRequest
	12, // 11: sequentialid.SequentialIDService.GetConfig:input_type -> sequentialid.GetConfigRequest
	14, // 12: sequentialid.SequentialIDService.UpdateConfig:input_type -> sequentialid.UpdateConfigRequest
	2,  // 13: sequentialid.SequentialIDService.GetNext:output_type -> sequentialid.GetNextResponse
	4,  // 14: sequentialid.SequentialIDService.GetNextBatch:output_type -> sequentialid.GetNextBatchResponse
	6,  // 15: sequentialid.SequentialIDService.ResetCounter:output_type -> sequentialid.ResetCounterResponse
	8,  // 16: sequentialid.SequentialIDService.GetStatus:output_type -> sequentialid.GetStatusResponse
	11, // 17: sequentialid.SequentialIDService.Health:output_type -> sequentialid.HealthResponse
	13, // 18: sequentialid.SequentialIDService.GetConfig:output_type -> sequentialid.GetConfigResponse
	15, // 19: sequentialid.SequentialIDService.UpdateConfig:output_type -> sequentialid.UpdateConfigResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_sequential_id_proto_init() }
func file_api_proto_sequential_id_proto_init() {
	if File_api_proto_sequential_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sequential_id_proto_rawDesc), len(file_api_proto_sequential_id_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_sequential_id_proto_goTypes,
		DependencyIndexes: file_api_proto_sequential_id_proto_depIdxs,
		EnumInfos:         file_api_proto_sequential_id_proto_enumTypes,
		MessageInfos:      file_api_proto_sequential_id_proto_msgTypes,
	}.Build()
	File_api_proto_sequential_id_proto = out.File
	file_api_proto_sequential_id_proto_goTypes = nil
	file_api_proto_sequential_id_proto_depIdxs = nil
}
